Mission04_eamado/Models/FanMailModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission04_eamado.Models
{
    public class FanMailModel
    {
        [Range(0, 100, ErrorMessage = "The value must be between 0 and 100")]
        public int Calc1 { get; set; }
        [Range(0, 100, ErrorMessage = "The value must be between 0 and 100")]
        public int Calc2 { get; set; }
        [Range(0, 100, ErrorMessage = "The value must be between 0 and 100")]
        public int Calc3 { get; set; }
        [Range(0, 100, ErrorMessage = "The value must be between 0 and 100")]
        public int Calc4 { get; set; }
        [Range(0, 100, ErrorMessage = "The value must be between 0 and 100")]
        public int Calc5 { get; set; }
        [Range(0, 100, ErrorMessage = "The value must be between 0 and 100")]
        public int Calc6 { get; set; }
        [Range(0, 100, ErrorMessage = "The value must be between 0 and 100")]
        public int Calc7 { get; set; }
    }
}

Mission04_eamado/Controllers/BlahController.cs
using Microsoft.AspNetCore.Mvc;
using Mission04_eamado.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission04_eamado.Controllers
{
    public class BlahController : Controller //inheritence ':'
    {
        public IActionResult Index()
        {
            return View(); //returning a view associated with the index view if nothing is inside view() parameters
        }
        [HttpGet]
        public IActionResult FanMail ()
        {
            return View();
        }
        [HttpPost]
        public IActionResult FanMail (FanMailModel model)
        {
            return View();
        }
    }
}

Mission04_eamado/Views/Blah/FanMail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model FanMailModel;

<h2>Calculator</h2>
<form method="post">
    <label class="nowrap">Assignments: </label>
    <input id="Assignments" asp-for="Calc1" /><br />
    <label class="nowrap">Group Projects: </label>
    <input id="GroupProjects" asp-for="Calc2" /><br />
    <label class="nowrap">Quizzes: </label>
    <input id="Quizzes" asp-for="Calc3" /><br />
    <label class="nowrap">Midterm Exam: </label>
    <input id="MidtermExam" asp-for="Calc4" /><br />
    <label class="nowrap">Final Exam: </label>
    <input id="FinalExam" asp-for="Calc5" /><br />
    <label class="nowrap">INTEX: </label>
    <input id="Intex" asp-for="Calc6" /><br />
    <input id="calcButton" type="submit" asp-for="Calc7" value="calculate" />
    <br />
    <div asp-validation-summary="All"></div>
    <div id="FinalGradeNumeric"></div>
    <div id="FinalGradeAlph"></div>
</form>
<br />
<script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
<script src="~/lib/jquery/jquery-3.6.3.min.js"></script>
<script src="~/js/FanMail.js"></script>  <!--Importing javascript file happens at the end of a file-->

Mission04_eamado/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Eliot Fan Club";
    ViewData["MyFavoriteISProfessor"] = "idk";
}

<link rel="shortcut icon" href="https://www.google.com/imgres?imgurl=https%3A%2F%2Flookaside.fbsbx.com%2Flookaside%2Fcrawler%2Fmedia%2F%3Fmedia_id%3D100063675544775&imgrefurl=https%3A%2F%2Fwww.facebook.com%2Fbyumarriott%2F&tbnid=AjGmDuxD31eWKM&vet=12ahUKEwjZ5rXmy_D8AhWiB0QIHUmkCVcQMygAegUIARDNAQ..i&docid=B85lGtqK8NBJjM&w=1050&h=1050&q=byu%20marriott%20schoool&ved=2ahUKEwjZ5rXmy_D8AhWiB0QIHUmkCVcQMygAegUIARDNAQ">


<h1>Welcome to my web page!</h1>
<img src="img/Eliot Profile Pic.jpeg" />
<h2> Eliot, (a.k.a 'The Hero') is a information systems student at byu</h2>
<br />
<h2>What I hope to get out of IS 413</h2>
<p>I hope to gain more coding skills throughout this course. specifically c# coding skills, and maybe some javascript and basic html skills so i can build a beautiful website easily. Honestly I would love to learn any foundational and advanced skills I can use later in life. </p>
<br />
<h2>Top 3 jobs I am most interested in pursuing when I graduate</h2>
<ol>
    <li>Mobiae applications developer</li>
    <li>API Engineer</li>
    <li>AI Engineer</li>
</ol>
<br />


<br />
<br />
<script src="lib/bootstrap/js/bootstrap.min.js"></script>
<script src="lib/jquery/jquery-3.6.3.min.js"></script>
<script src="js/FanMail.js"></script> <!--Importing javascript file happens at the end of a file-->

Mission04_eamado/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <!--all pages will use this template-->
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" type="image/x-icon" href="img/Eliot Profile Pic.jpeg" />
    <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="css/StyleSheet.css" rel="stylesheet" />
</head>
<body>
    <nav>
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="FanMail">Calculator</a>
    </nav>
    <div>
        @RenderBody() <!--Is were everything else will go on index.cshtml-->
    </div>


    <script src="lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="lib/jquery/jquery-3.6.3.min.js"></script>
</body>
</html>